package service

import (
	"context"
	"testing"
	"time"

	"github.com/company/cjpayment/internal/repository"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// Use the existing MockRechargeOrderRepository from mocks_test.go

func TestBankService_InitiateBankTransfer(t *testing.T) {
	mockRepo := new(MockRechargeOrderRepository)
	config := &BankConfig{
		APIBaseURL:    "https://api.bank.example.com",
		APIKey:        "test-key",
		APISecret:     "test-secret",
		SignatureKey:  "test-signature-key",
		Timeout:       30 * time.Second,
		RetryAttempts: 3,
	}
	
	service := NewBankService(mockRepo, config)
	ctx := context.Background()
	
	// Test data
	orderID := uuid.New()
	order := &repository.RechargeOrder{
		ID:          orderID,
		OrderNumber: "CJ202501011234567890",
		PaymentType: "public",
		Status:      "pending",
		Amount:      decimal.NewFromFloat(1000.00),
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}
	
	req := &InitiateBankTransferRequest{
		OrderID:         orderID,
		PayerName:       "Test Company",
		PayerAccount:    "1234567890",
		Amount:          decimal.NewFromFloat(1000.00),
		ReceiverName:    "Receive Company",
		ReceiverAccount: "0987654321",
		BankName:        "Test Bank",
		BankBranch:      nil,
		Purpose:         "Test transfer",
		NotifyURL:       "https://example.com/callback",
		ReturnURL:       "https://example.com/return",
	}

	// Mock expectations
	mockRepo.On("GetByID", ctx, orderID).Return(order, nil)
	mockRepo.On("Update", ctx, mock.AnythingOfType("*repository.RechargeOrder")).Return(nil)

	// Execute
	response, err := service.InitiateBankTransfer(ctx, req)

	// Assertions
	assert.NoError(t, err)
	assert.NotNil(t, response)
	assert.Equal(t, orderID, response.OrderID)
	assert.Equal(t, BankTransferStatusPending, response.Status)
	assert.NotEmpty(t, response.TransferID)
	assert.NotEmpty(t, response.TransferURL)
	assert.NotEmpty(t, response.BankReference)
	
	mockRepo.AssertExpectations(t)
}

func TestBankService_InitiateBankTransfer_InvalidPaymentType(t *testing.T) {
	mockRepo := new(MockRechargeOrderRepository)
	config := &BankConfig{}
	service := NewBankService(mockRepo, config)
	ctx := context.Background()
	
	orderID := uuid.New()
	order := &repository.RechargeOrder{
		ID:          orderID,
		PaymentType: "private", // Invalid for bank transfer
		Status:      "pending",
	}
	
	req := &InitiateBankTransferRequest{
		OrderID: orderID,
	}

	mockRepo.On("GetByID", ctx, orderID).Return(order, nil)

	// Execute
	response, err := service.InitiateBankTransfer(ctx, req)

	// Assertions
	assert.Error(t, err)
	assert.Nil(t, response)
	assert.Contains(t, err.Error(), "bank transfer is only available for public recharge orders")
	
	mockRepo.AssertExpectations(t)
}

func TestBankService_ProcessBankCallback(t *testing.T) {
	mockRepo := new(MockRechargeOrderRepository)
	config := &BankConfig{
		SignatureKey: "test-signature-key",
	}
	service := NewBankService(mockRepo, config)
	ctx := context.Background()
	
	orderID := uuid.New()
	order := &repository.RechargeOrder{
		ID:     orderID,
		Amount: decimal.NewFromFloat(1000.00),
		Status: "pending",
	}
	
	// Create a valid callback (signature will be generated by the service)
	callback := &BankCallbackRequest{
		TransferID:    "BT20250101120000abcd1234",
		OrderID:       orderID.String(),
		Status:        BankTransferStatusSuccess,
		Amount:        decimal.NewFromFloat(1000.00),
		PayerName:     "Test Company",
		PayerAccount:  "1234567890",
		TransferTime:  time.Now(),
		BankReference: "REF123456",
		Timestamp:     time.Now().Unix(),
	}
	
	// Generate signature for the callback
	bankService := service.(*bankService)
	data := map[string]interface{}{
		"transfer_id":    callback.TransferID,
		"order_id":       callback.OrderID,
		"status":         callback.Status,
		"amount":         callback.Amount.String(),
		"payer_name":     callback.PayerName,
		"payer_account":  callback.PayerAccount,
		"bank_reference": callback.BankReference,
		"timestamp":      callback.Timestamp,
	}
	signature, _ := bankService.generateSignature(data)
	callback.Signature = signature

	mockRepo.On("GetByID", ctx, orderID).Return(order, nil)
	mockRepo.On("Update", ctx, mock.AnythingOfType("*repository.RechargeOrder")).Return(nil)

	// Execute
	response, err := service.ProcessBankCallback(ctx, callback)

	// Assertions
	assert.NoError(t, err)
	assert.NotNil(t, response)
	assert.True(t, response.Success)
	assert.Equal(t, "SUCCESS", response.Code)
	
	mockRepo.AssertExpectations(t)
}

func TestBankService_ProcessBankCallback_AmountMismatch(t *testing.T) {
	mockRepo := new(MockRechargeOrderRepository)
	config := &BankConfig{
		SignatureKey: "test-signature-key",
	}
	service := NewBankService(mockRepo, config)
	ctx := context.Background()
	
	orderID := uuid.New()
	order := &repository.RechargeOrder{
		ID:     orderID,
		Amount: decimal.NewFromFloat(1000.00), // Different from callback amount
		Status: "pending",
	}
	
	callback := &BankCallbackRequest{
		TransferID:    "BT20250101120000abcd1234",
		OrderID:       orderID.String(),
		Status:        BankTransferStatusSuccess,
		Amount:        decimal.NewFromFloat(2000.00), // Different amount
		PayerName:     "Test Company",
		PayerAccount:  "1234567890",
		TransferTime:  time.Now(),
		BankReference: "REF123456",
		Timestamp:     time.Now().Unix(),
	}
	
	// Generate signature
	bankService := service.(*bankService)
	data := map[string]interface{}{
		"transfer_id":    callback.TransferID,
		"order_id":       callback.OrderID,
		"status":         callback.Status,
		"amount":         callback.Amount.String(),
		"payer_name":     callback.PayerName,
		"payer_account":  callback.PayerAccount,
		"bank_reference": callback.BankReference,
		"timestamp":      callback.Timestamp,
	}
	signature, _ := bankService.generateSignature(data)
	callback.Signature = signature

	mockRepo.On("GetByID", ctx, orderID).Return(order, nil)

	// Execute
	response, err := service.ProcessBankCallback(ctx, callback)

	// Assertions
	assert.NoError(t, err)
	assert.NotNil(t, response)
	assert.False(t, response.Success)
	assert.Equal(t, "AMOUNT_MISMATCH", response.Code)
	
	mockRepo.AssertExpectations(t)
}

func TestBankService_GetBankTransferStatus(t *testing.T) {
	mockRepo := new(MockRechargeOrderRepository)
	config := &BankConfig{}
	service := NewBankService(mockRepo, config)
	ctx := context.Background()
	
	orderID := uuid.New()
	order := &repository.RechargeOrder{
		ID:        orderID,
		Status:    "paid",
		Amount:    decimal.NewFromFloat(1000.00),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	
	mockRepo.On("GetByID", ctx, orderID).Return(order, nil)

	// Execute
	status, err := service.GetBankTransferStatus(ctx, orderID)

	// Assertions
	assert.NoError(t, err)
	assert.NotNil(t, status)
	assert.Equal(t, orderID, status.OrderID)
	assert.Equal(t, BankTransferStatusSuccess, status.Status)
	assert.Equal(t, order.Amount, status.Amount)
	
	mockRepo.AssertExpectations(t)
}

func TestBankService_ValidateBankCallback(t *testing.T) {
	service := NewBankService(nil, &BankConfig{})
	ctx := context.Background()
	
	tests := []struct {
		name        string
		callback    *BankCallbackRequest
		expectError bool
	}{
		{
			name: "Valid callback",
			callback: &BankCallbackRequest{
				Status:    BankTransferStatusSuccess,
				Amount:    decimal.NewFromFloat(1000.00),
				Timestamp: time.Now().Unix(),
			},
			expectError: false,
		},
		{
			name: "Invalid status",
			callback: &BankCallbackRequest{
				Status:    "invalid_status",
				Amount:    decimal.NewFromFloat(1000.00),
				Timestamp: time.Now().Unix(),
			},
			expectError: true,
		},
		{
			name: "Invalid amount",
			callback: &BankCallbackRequest{
				Status:    BankTransferStatusSuccess,
				Amount:    decimal.NewFromFloat(-100.00),
				Timestamp: time.Now().Unix(),
			},
			expectError: true,
		},
		{
			name: "Old timestamp",
			callback: &BankCallbackRequest{
				Status:    BankTransferStatusSuccess,
				Amount:    decimal.NewFromFloat(1000.00),
				Timestamp: time.Now().Unix() - 600, // 10 minutes ago
			},
			expectError: true,
		},
	}
	
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := service.ValidateBankCallback(ctx, tt.callback)
			if tt.expectError {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestBankService_GenerateSignature(t *testing.T) {
	config := &BankConfig{
		SignatureKey: "test-signature-key",
	}
	service := NewBankService(nil, config).(*bankService)
	
	data := map[string]interface{}{
		"transfer_id": "BT20250101120000abcd1234",
		"order_id":    "12345678-1234-1234-1234-123456789012",
		"status":      "success",
		"amount":      "1000.00",
	}
	
	// Generate signature
	signature1, err1 := service.generateSignature(data)
	signature2, err2 := service.generateSignature(data)
	
	// Assertions
	assert.NoError(t, err1)
	assert.NoError(t, err2)
	assert.NotEmpty(t, signature1)
	assert.Equal(t, signature1, signature2) // Same data should produce same signature
	
	// Different data should produce different signature
	data["amount"] = "2000.00"
	signature3, err3 := service.generateSignature(data)
	assert.NoError(t, err3)
	assert.NotEqual(t, signature1, signature3)
}